name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Despliega cuando hay push a la rama main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # O el directorio correcto para el despliegue
          publish_branch: gh-pages  # Especifica la rama de GitHub Pages
          force_orphan: true  # Crea la rama si no existe
